### ISSUE TITLE
Violating PUL

### ISSUE THREAD

**Issue by danielkihlgren** [direktdemokraterna/dd#1]
The file data.txt is violating PUL. That file should not be public.

**Comment by anderslonnfalt** [comment]
Tack för tipset. Det är givetvis inte information som ska vara där utan
något som råkat följa med en ovarsam commit.

2017-01-11 13:25 GMT+01:00 Daniel <notifications@github.com>:

**Comment by anderslonnfalt** [comment]
Vissa saker börja klarna lite. Den okända daniel verkar vara Daniel
Kihlgren, för mig ganska okänd partimedlem. Jag har frågat honom varför han
inte är med i utvecklingen, han verkar kunna ett och annat om Git och skrev
dessutom på forumet och frågade när vi skulle få git-integrering när vi var
i uppstarten med det nya medlemssystemet.

Dessutom har jag kollat i lagboken och konstaterat att brott mot
personuppgiftslagen bara ger sex månaders fängelse. Knappt mer än illegal
nedladdning. Jag kan säkert sitta av båda samtidigt när det blir aktuellt.

2017-01-11 14:59 GMT+01:00 Anders Lönnfält <anders@lonnfalt.se>:

**Comment by danielkihlgren** [comment]
Closing this issue, the files has been cleaned from repository.
